apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcd
  namespace: mysqlcd
  labels:
    app: mysqlcd
spec:
  selector:
    matchLabels:
      app: mysqlcd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlcd
        tier: mysql
    spec:
      containers:
      - name: mysqlcd
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
          - name: mysqld
            containerPort: 3306
            protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
