apiVersion: v1
kind: Service
metadata:
  annotations:
     field.cattle.io/description: Mysql ClusterIP
  name: mysqlcd
  # Add labels and annotations as per your requirements
spec:
  ports:
    - name: mysqld
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
     app: mysqlcd
  type: NodePort     
    # Specify the labels to match the RabbitMQ pods
